# permissions for end users to edit permissionedroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permissionedrole-editor-role
rules:
- apiGroups:
  - rbac-controller.pliu.github.com
  resources:
  - permissionedroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac-controller.pliu.github.com
  resources:
  - permissionedroles/status
  verbs:
  - get
