# permissions for end users to view permissionedroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permissionedrole-viewer-role
rules:
- apiGroups:
  - rbac-controller.pliu.github.com
  resources:
  - permissionedroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac-controller.pliu.github.com
  resources:
  - permissionedroles/status
  verbs:
  - get
