# permissions for end users to view permissionedclusterroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: permissionedclusterrole-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rbac-controller
    app.kubernetes.io/part-of: rbac-controller
    app.kubernetes.io/managed-by: kustomize
  name: permissionedclusterrole-viewer-role
rules:
- apiGroups:
  - rbac.pliu.github.com.pliu.github.com
  resources:
  - permissionedclusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.pliu.github.com.pliu.github.com
  resources:
  - permissionedclusterroles/status
  verbs:
  - get
